name: Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Clone
              uses: actions/checkout@v3

            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Docs
              run: npm install

            - name: Build Docs
              run: npm run build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: .vitepress/dist
                  cname: suboptimalstudio.com
